# -*- coding: utf-8 -*-
"""historical_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GU5y0HCJ4IhMUOw8lBOdhsdLDouDPLRW

# Historical Price-Revenue Lookup (Alternative to Elasticity)

**Approach:** For events similar to the one you're pricing (same genre, similar demand level), what price ranges historically produced the most revenue?
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("/Users/ethanc/RnA/data/test_sample_cleaned_v2.csv")
print(f"Date range: {df['event_date'].min()} to {df['event_date'].max()}")

df.shape

# Create revenue: price × demand
df['revenue'] = df['ticket_price_avg'] * df['avg_tickets_sold']
df['demand_tier'] = pd.qcut(df['avg_tickets_sold'], q=3, labels=['Low', 'Mid', 'High'])
df['price_bin'] = pd.qcut(df['ticket_price_avg'], q=5, labels=['Very Low', 'Low', 'Mid', 'High', 'Very High'])

# Simplify genres into major categories
def simplify_genre(g):
    if pd.isna(g): return 'Other'
    if 'Latin' in g: return 'Latin'
    if 'Pop / Rock' in g: return 'Pop / Rock'
    if 'Country' in g: return 'Country'
    if 'Rap' in g or 'HipHop' in g: return 'Rap / HipHop'
    if 'Dance' in g or 'Electronic' in g: return 'Dance / Electronic'
    return 'Other'

df['genre_group'] = df['genre'].apply(simplify_genre)


print(df['demand_tier'].value_counts().sort_index())
print()

print(df['price_bin'].value_counts().sort_index())
print()

print(df['genre_group'].value_counts())

"""## Lookup Table

For each combination of genre and demand level, we calculate the average revenue at each price level, just historical averages.
"""

lookup = df.groupby(['genre_group', 'demand_tier', 'price_bin'], observed=True).agg(
    avg_revenue=('revenue', 'mean'),
    median_revenue=('revenue', 'median'),
    avg_demand=('avg_tickets_sold', 'mean'),
    avg_price=('ticket_price_avg', 'mean'),
    num_events=('revenue', 'count')
).reset_index()


# best price level for each
print("\n\nBEST PRICE LEVEL BY GROUP (highest avg revenue):")
print("=" * 60)
best = lookup.loc[lookup.groupby(['genre_group', 'demand_tier'], observed=True)['avg_revenue'].idxmax()]
for _, row in best.iterrows():
    print(f"  {row['genre_group']:20s} | {row['demand_tier']:4s} demand | Best price: {row['price_bin']:<10s} ({row['num_events']:.0f} events)")

"""## DataVis Revenue by Price Level

For each genre, we show how revenue changes across price levels for high-demand artists.
"""

# plot revenue by price level for each genre (high demand only)
genres_to_plot = ['Pop / Rock', 'Latin', 'Country', 'Rap / HipHop']
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for i, genre in enumerate(genres_to_plot):
    ax = axes[i]
    subset = lookup[(lookup['genre_group'] == genre) & (lookup['demand_tier'] == 'High')]

    if len(subset) == 0:
        ax.text(0.5, 0.5, f'Not enough High demand\nevents for {genre}',
                ha='center', va='center', transform=ax.transAxes)
        ax.set_title(genre)
        continue

    colors = ['#3498db' if r != subset['avg_revenue'].max() else '#e74c3c' for r in subset['avg_revenue']]
    bars = ax.bar(range(len(subset)), subset['avg_revenue'], color=colors, edgecolor='white')
    ax.set_xticks(range(len(subset)))
    ax.set_xticklabels(subset['price_bin'], rotation=30, ha='right')
    ax.set_ylabel('Average Revenue')
    ax.set_title(f'{genre} — High Demand Artists')

    #event count labels on bars
    for j, (bar, count) in enumerate(zip(bars, subset['num_events'])):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
                f'n={int(count)}', ha='center', va='bottom', fontsize=9, color='gray')

plt.suptitle('Revenue by Price Level (High-Demand Events Only)', fontsize=14, fontweight='bold')
plt.tight_layout()
#plt.show()

subset = lookup[(lookup['genre_group'] == 'Pop / Rock') & 
                (lookup['demand_tier'] == 'High')]

# % change in demand / % change in price between adjacent price bins
subset = subset.sort_values('avg_price')
subset['pct_change_demand'] = subset['avg_demand'].pct_change()
subset['pct_change_price'] = subset['avg_price'].pct_change()
subset['elasticity'] = subset['pct_change_demand'] / subset['pct_change_price']

print(subset[['price_bin', 'avg_price', 'avg_demand', 'elasticity']])


