# -*- coding: utf-8 -*-
"""Two-stage model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUfgo-t4GTl7x2FqChKIcPC0tlG651hw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeCV
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

"""## Load the dataset"""

df = pd.read_csv("/Users/ethanc/RnA/data/test_sample_cleaned_v2.csv")
df.head(10)

"""# Dataset info:"""

print("Dataset Shape:", df.shape)
print("Dataset Info:")
df.info(verbose=True, show_counts=True)

"""## Feature Sorting:"""

#rename features with special characters:
import re

df.columns = (
    df.columns
      .astype(str)
      .str.replace(r"[\[\]<>]", "", regex=True)  # remove [ ] <
      .str.replace(r"[^0-9a-zA-Z_]+", "_", regex=True)  # replace spaces/punct with _
      .str.strip("_")
)

# add an indicator for whether a concert is sold out
#df['is_soldout'] = (df['avg_capacity_sold'] >= 99.5).astype(int)

#Drop features that are not helpful for training:
LEAKAGE_VARS = [
    "avg_gross_usd", "avg_event_capacity",
    "avg_capacity_sold", "ticket_price_min", "ticket_price_max", "ticket_price_avg","number_of_shows"
]
NON_FEATURES = ["eventid", "event_date", "support", "venue", "city", "state", "country",
                "market", "company_type", "promoter", "genre","headliner","gt_date_range",
                "census_market_name", "market_clean", "acs_market","day_of_week", "month","last_album_date",
                "is_missing_album_dates","is_missing_support"]
DROP_IF_PRESENT = ["Currency", "Prev_Event_Gross", "genre_cleaned_other", "population"]

def drop_columns_if_present(df, cols):
    existing = [c for c in cols if c in df.columns]
    return df.drop(columns=existing, errors="ignore"), existing

cols = df.columns
df, dropped_cols = drop_columns_if_present(df, LEAKAGE_VARS + NON_FEATURES + DROP_IF_PRESENT)

#remove some one-hot encoding features:
cols_to_drop = [col for col in df.columns if
                col.startswith("headliner_cleaned_") or
                col.startswith("support_cleaned_") or
                col.startswith("venue_cleaned_") or
                col.startswith("promoter_cleaned_") or
                col.startswith("company_type_cleaned_")]

df = df.drop(columns=cols_to_drop)

#Convert bolean columns (True/False) to integers:
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

print("Dataset Shape:", df.shape)
pd.set_option("display.max_columns", None)

df.head()

df.columns

"""# Splitting Training and Testing dataset:"""

from xgboost import XGBRegressor
TARGET_COL = "avg_tickets_sold"
X = df.drop(columns=[TARGET_COL] + LEAKAGE_VARS + NON_FEATURES, errors="ignore").copy()
y = df[TARGET_COL].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# Model 1: XGBoost"""

model = XGBRegressor(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.7,
    reg_lambda=5.0,
    random_state=42,
    min_child_weight=5
)
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred  = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_train_pred = model.predict(X_train)
y_test_pred  = model.predict(X_test)

metrics = {
    "Train_MAE": mean_absolute_error(y_train, y_train_pred),
    "Test_MAE":  mean_absolute_error(y_test, y_test_pred),

    "Train_MSE": mean_squared_error(y_train, y_train_pred),
    "Test_MSE":  mean_squared_error(y_test, y_test_pred),

    "Train_RMSE": mean_squared_error(y_train, y_train_pred) ** 0.5,
    "Test_RMSE":  mean_squared_error(y_test, y_test_pred) ** 0.5,

    "Train_R2": r2_score(y_train, y_train_pred),
    "Test_R2":  r2_score(y_test, y_test_pred),
}


print(
    f"Train -> MAE: {metrics['Train_MAE']:.2f}  "
    f"RMSE: {metrics['Train_RMSE']:.2f}  "
    f"R^2: {metrics['Train_R2']:.4f}"
)

print(
    f"Test  -> MAE: {metrics['Test_MAE']:.2f}  "
    f"RMSE: {metrics['Test_RMSE']:.2f}  "
    f"R^2: {metrics['Test_R2']:.4f}"
)

df['fill_rate'] = df['avg_tickets_sold'] / df['avg_event_capacity']
df['fill_rate'] = df['fill_rate'].clip(0, 1)

print(df['fill_rate'].describe())
print(df['fill_rate'].hist(bins=20))



from xgboost import plot_importance

# feature names + importance scores
imp = pd.Series(model.feature_importances_, index=X_train.columns)

top15 = imp.sort_values(ascending=False).head(15)

plt.figure()
top15.sort_values().plot(kind="barh")
plt.xlabel("Feature importance")
plt.title("Top 15 Feature Importances (XGBoost)")
plt.show()

"""# Model 2: LightGBM"""

'''import lightgbm as lgb
model = lgb.LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    num_leaves=20,
    max_depth=3,
    min_child_samples=20,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=1.0,
    reg_lambda=5.0,
    random_state=42
)

model.fit(X_train, y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

def evaluate(y_true, y_pred, name):
    print(name)
    print("MAE:", mean_absolute_error(y_true, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_true, y_pred)))
    print("R2:", r2_score(y_true, y_pred))
    print()

evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

# feature names + importance scores
# Get gain importance
importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': model.booster_.feature_importance(importance_type='gain')
})

# Normalize
importance['importance'] = importance['importance'] / importance['importance'].sum()

# Sort
importance = importance.sort_values(by='importance', ascending=False)

# Plot
plt.figure(figsize=(8,6))
plt.barh(
    importance['feature'][:15][::-1],
    importance['importance'][:15][::-1]
)

plt.xlabel("Feature Importance")
plt.title("Top 15 Feature Importances (LightGBM)")
plt.xlim(0, importance['importance'][:15].max() * 1.1)  # similar scaling

plt.show()

"""## Model 3: Lasso Regression"""

from sklearn.linear_model import Lasso
lasso_model = Lasso(
    alpha=0.01,
    max_iter=10000,
    random_state=42
)

lasso_model.fit(X_train, y_train)

y_train_pred = lasso_model.predict(X_train)
y_test_pred = lasso_model.predict(X_test)

def evaluate(y_true, y_pred, name):
    print(name)
    print("MAE:", mean_absolute_error(y_true, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_true, y_pred)))
    print("R2:", r2_score(y_true, y_pred))
    print()

evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

# feature importance:
importance = np.abs(lasso_model.coef_)

lasso_importance = (
    pd.DataFrame({
        'feature': X_train.columns,
        'importance': importance
    })
    .sort_values(by='importance', ascending=False)
)

print(lasso_importance.head(15))
import matplotlib.pyplot as plt

top = lasso_importance.head(15)

plt.figure(figsize=(8,6))
plt.barh(top['feature'][::-1], top['importance'][::-1])
plt.title("Top 15 Features (Lasso)")
plt.xlabel("Coefficient Magnitude")
plt.show()

"""## Model 4: Random Forest"""

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions
y_pred_train = rf_model.predict(X_train)
y_pred_test = rf_model.predict(X_test)

print("Train:")
print("MAE:", mean_absolute_error(y_train, y_pred_train))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_pred_train)))
print("R2:", r2_score(y_train, y_pred_train))

print("\nTest:")
print("MAE:", mean_absolute_error(y_test, y_pred_test))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_test)))
print("R2:", r2_score(y_test, y_pred_test))

# Get feature importances
importances = rf_model.feature_importances_

# Normalize (so sum = 1, like XGBoost)
importances = importances / importances.sum()

feature_names = X_train.columns  # if DataFrame

feat_df = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values(by='importance', ascending=False)

# Top 15
top_features = feat_df.head(15)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.barh(top_features['feature'], top_features['importance'])
plt.gca().invert_yaxis()

plt.title("Top 15 Feature Importances (Random Forest)")
plt.xlabel("Feature importance")

plt.show()

"""## Model 5: Catboost"""

from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    random_state=42,
    verbose=100
)

cat_model.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predictions
y_pred_train = cat_model.predict(X_train)
y_pred_test = cat_model.predict(X_test)

print("Train:")
print("MAE:", mean_absolute_error(y_train, y_pred_train))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_pred_train)))
print("R2:", r2_score(y_train, y_pred_train))

print("\nTest:")
print("MAE:", mean_absolute_error(y_test, y_pred_test))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_test)))
print("R2:", r2_score(y_test, y_pred_test))

import pandas as pd
import matplotlib.pyplot as plt

# Get importance
importances = cat_model.get_feature_importance()

# Normalize
importances = importances / importances.sum()

feature_names = X_train.columns

feat_df = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values(by='importance', ascending=False)

top_features = feat_df.head(15)

# Plot
plt.figure(figsize=(8,6))
plt.barh(top_features['feature'], top_features['importance'])
plt.gca().invert_yaxis()

plt.title("Top 15 Feature Importances (CatBoost)")
plt.xlabel("Feature importance")

plt.show()'''